[package]
name = "rust_os_v1"
version = "0.1.0"
authors = ["Griffin Morgan <gmmorgan96@ghostosproject.com>"]


[dependencies]
rlibc = "1.0"
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]